# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=120, verbose_name='apellido')),
                ('password', models.CharField(max_length=120, verbose_name='Password')),
                ('codigo', models.CharField(max_length=120, verbose_name='uuid')),
            ],
            options={
                'verbose_name': 'Usuarios',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
