# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2016-12-12 12:12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='modified',
            field=models.DateTimeField(auto_now=True, default='2016-12-12 12:12'),
            preserve_default=False,
        ),
    ]
