# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20160427_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True, verbose_name='Key'),
        ),
    ]
